#!/bin/sh
set -e

dirs=$(glide nv -x | grep -v logging | grep -v wix)

for pkg in $dirs; do
  go tool vet -all -printfuncs=Criticalf,Infof,Warningf,Debugf,Tracef $pkg
  for os in $@; do
    if [ $os != "windows" ]; then
      GOOS=$os golint -set_exit_status $pkg
    else
      GOOS=$os golint -set_exit_status -min_confidence=0.9 $pkg
    fi
  done
done
